echo "hello project"
echo "welcome devops team"
echo "hello maheboob"
echo "hello shafi"
echo "new dev branch"
echo "newly devbrach created by Eliyas"
echo "git pull"
echo "git stash"
echo "created by me"
echo "done"
echo "shafi"
